name: Minify & deploy

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: |
          npm install cssnano html-minifier postcss postcss-cli --save-dev
        
      - name: Configure postcss
        run: |
          echo "module.exports = {plugins: [require('cssnano')]}" > postcss.config.js

      - name: Create temp dist dir
        run: |
          mkdir -p dist

      - name: Minify HTML
        run: |
          for file in *.html; do
            npx html-minifier --collapse-whitespace --remove-comments --minify-js true --minify-css true --output dist/$file $file
          done
            
      - name: Minify CSS
        run: |
          for file in *.css; do
            npx postcss $file > dist/$file
          done

      - name: Remove the old files
        run: |
          rm *.html *.css
      
      - name: Move the new files to root
        run: |
          mv dist/* .
      
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-


      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
